2021-02-10 14:59:01.757 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package azureml-train-automl missing from dependencies file.
2021-02-10 14:59:01.757 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: azureml-train-automl==1.19.0.*
2021-02-10 14:59:01.758 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package pandas missing from dependencies file.
2021-02-10 14:59:01.758 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: pandas==0.25.1
2021-02-10 14:59:01.758 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package psutil missing from dependencies file.
2021-02-10 14:59:01.758 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: psutil>5.0.0,<6.0.0
2021-02-10 14:59:01.759 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package scikit-learn missing from dependencies file.
2021-02-10 14:59:01.759 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: scikit-learn==0.22.1
2021-02-10 14:59:01.759 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package numpy missing from dependencies file.
2021-02-10 14:59:01.759 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: numpy~=1.18.0
2021-02-10 14:59:01.760 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package py-xgboost missing from dependencies file.
2021-02-10 14:59:01.760 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: py-xgboost<=0.90
2021-02-10 14:59:01.761 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package inference-schema missing from dependencies file.
2021-02-10 14:59:01.761 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package fbprophet missing from dependencies file.
2021-02-10 14:59:01.761 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: fbprophet==0.5
2021-02-10 14:59:01.762 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package setuptools-git missing from dependencies file.
2021-02-10 14:59:01.766 - INFO - 216872 - azureml.train.automl._azureautomlclient._validate_input:663 - Start data validation.
2021-02-10 14:59:19.060 - INFO - 216872 - azureml.train.automl._azureautomlclient._validate_input:676 - Validation service found the data has no errors.
2021-02-10 14:59:19.060 - INFO - 216872 - azureml.train.automl._azureautomlclient._create_parent_run_for_remote:541 - Start creating parent run.
2021-02-10 14:59:34.876 - INFO - 216872 - azureml.train.automl._azureautomlclient._create_parent_run_for_remote:561 - [ParentRunID:AutoML_b41462f6-0463-40e6-8338-e0c53c2f277f] Remote run using input X and y.
2021-02-10 14:59:35.818 - INFO - 216872 - azureml.train.automl._azureautomlclient._create_parent_run_for_remote:574 - Parent Run ID: AutoML_b41462f6-0463-40e6-8338-e0c53c2f277f
2021-02-10 14:59:35.818 - INFO - 216872 - azureml.train.automl._azureautomlclient._fit_remote_core:502 - Starting a snapshot run (snapshot_id : None)
2021-02-10 15:03:43.484 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package azureml-train-automl missing from dependencies file.
2021-02-10 15:03:43.485 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: azureml-train-automl==1.19.0.*
2021-02-10 15:03:43.485 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package pandas missing from dependencies file.
2021-02-10 15:03:43.486 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: pandas==0.25.1
2021-02-10 15:03:43.486 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package psutil missing from dependencies file.
2021-02-10 15:03:43.486 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: psutil>5.0.0,<6.0.0
2021-02-10 15:03:43.487 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package scikit-learn missing from dependencies file.
2021-02-10 15:03:43.487 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: scikit-learn==0.22.1
2021-02-10 15:03:43.487 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package numpy missing from dependencies file.
2021-02-10 15:03:43.487 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: numpy~=1.18.0
2021-02-10 15:03:43.487 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package py-xgboost missing from dependencies file.
2021-02-10 15:03:43.488 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: py-xgboost<=0.90
2021-02-10 15:03:43.488 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package inference-schema missing from dependencies file.
2021-02-10 15:03:43.489 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package fbprophet missing from dependencies file.
2021-02-10 15:03:43.489 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: fbprophet==0.5
2021-02-10 15:03:43.489 - INFO - 216872 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package setuptools-git missing from dependencies file.
2021-02-10 15:03:43.495 - INFO - 216872 - azureml.train.automl._azureautomlclient._validate_input:663 - Start data validation.
2021-02-10 15:03:45.077 - INFO - 216872 - azureml.train.automl._azureautomlclient._validate_input:676 - Validation service found the data has no errors.
2021-02-10 15:03:45.077 - INFO - 216872 - azureml.train.automl._azureautomlclient._create_parent_run_for_remote:541 - Start creating parent run.
2021-02-10 15:04:20.816 - INFO - 216872 - azureml.train.automl._azureautomlclient._create_parent_run_for_remote:561 - [ParentRunID:AutoML_2acb775a-f78b-43dc-b3d9-078f168cbe4a] Remote run using input X and y.
2021-02-10 15:04:36.650 - INFO - 216872 - azureml.train.automl._azureautomlclient._create_parent_run_for_remote:574 - Parent Run ID: AutoML_2acb775a-f78b-43dc-b3d9-078f168cbe4a
2021-02-10 15:04:36.651 - INFO - 216872 - azureml.train.automl._azureautomlclient._fit_remote_core:502 - Starting a snapshot run (snapshot_id : None)
2021-02-10 17:16:43.669 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package azureml-train-automl missing from dependencies file.
2021-02-10 17:16:43.669 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: azureml-train-automl==1.19.0.*
2021-02-10 17:16:43.670 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package pandas missing from dependencies file.
2021-02-10 17:16:43.670 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: pandas==0.25.1
2021-02-10 17:16:43.671 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package psutil missing from dependencies file.
2021-02-10 17:16:43.671 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: psutil>5.0.0,<6.0.0
2021-02-10 17:16:43.671 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package scikit-learn missing from dependencies file.
2021-02-10 17:16:43.672 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: scikit-learn==0.22.1
2021-02-10 17:16:43.672 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package numpy missing from dependencies file.
2021-02-10 17:16:43.672 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: numpy~=1.18.0
2021-02-10 17:16:43.673 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package py-xgboost missing from dependencies file.
2021-02-10 17:16:43.673 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: py-xgboost<=0.90
2021-02-10 17:16:43.673 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package inference-schema missing from dependencies file.
2021-02-10 17:16:43.674 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package fbprophet missing from dependencies file.
2021-02-10 17:16:43.674 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: fbprophet==0.5
2021-02-10 17:16:43.675 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package setuptools-git missing from dependencies file.
2021-02-10 17:16:43.679 - INFO - 275796 - azureml.train.automl._azureautomlclient._validate_input:663 - Start data validation.
2021-02-10 17:16:49.023 - CRITICAL - 275796 - azureml.train.automl._azureautomlclient.log_traceback:224 - Type: ValidationError
Class: ValidationException
Message: ValidationException:
	Message: Validation error(s): [{
    "additional_properties": {
        "debugInfo": null
    },
    "code": "UserError",
    "severity": 2,
    "message": "Y is empty",
    "message_format": "{dataName} is empty",
    "message_parameters": {
        "dataName": "Y"
    },
    "reference_code": null,
    "details_uri": null,
    "target": "training_data",
    "details": [
        {
            "additional_properties": {
                "debugInfo": null
            },
            "code": null,
            "severity": null,
            "message": "null",
            "message_format": null,
            "message_parameters": {},
            "reference_code": null,
            "details_uri": null,
            "target": null,
            "details": [],
            "inner_error": null
        }
    ],
    "inner_error": {
        "additional_properties": {},
        "code": "BadData",
        "inner_error": {
            "additional_properties": {},
            "code": "EmptyData",
            "inner_error": null
        }
    }
}]
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "ValidationError"
        },
        "message": "Validation error(s): [{\n    \"additional_properties\": {\n        \"debugInfo\": null\n    },\n    \"code\": \"UserError\",\n    \"severity\": 2,\n    \"message\": \"Y is empty\",\n    \"message_format\": \"{dataName} is empty\",\n    \"message_parameters\": {\n        \"dataName\": \"Y\"\n    },\n    \"reference_code\": null,\n    \"details_uri\": null,\n    \"target\": \"training_data\",\n    \"details\": [\n        {\n            \"additional_properties\": {\n                \"debugInfo\": null\n            },\n            \"code\": null,\n            \"severity\": null,\n            \"message\": \"null\",\n            \"message_format\": null,\n            \"message_parameters\": {},\n            \"reference_code\": null,\n            \"details_uri\": null,\n            \"target\": null,\n            \"details\": [],\n            \"inner_error\": null\n        }\n    ],\n    \"inner_error\": {\n        \"additional_properties\": {},\n        \"code\": \"BadData\",\n        \"inner_error\": {\n            \"additional_properties\": {},\n            \"code\": \"EmptyData\",\n            \"inner_error\": null\n        }\n    }\n}]"
    }
}
Traceback:
  File "_azureautomlclient.py", line 409, in fit
    test_data=test_data)
  File "_azureautomlclient.py", line 423, in _fit_remote
    validation_data=validation_data, test_data=test_data)
  File "_azureautomlclient.py", line 486, in _fit_remote_core
    training_data=training_data, validation_data=validation_data, test_data=test_data)
  File "_azureautomlclient.py", line 537, in _create_parent_run_for_remote
    test_data=test_data
  File "_azureautomlclient.py", line 616, in _create_and_validate_parent_run_dto
    self._validate_input(parent_run_dto)
  File "_azureautomlclient.py", line 694, in _validate_input
    "Validation failed. Please fix the data or settings following the validation results."

ExceptionTarget: Unspecified
2021-02-10 17:16:49.023 - INFO - 275796 - azureml.train.automl._azureautomlclient._fail_parent_run:846 - No parent run to fail
2021-02-10 17:18:43.586 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package azureml-train-automl missing from dependencies file.
2021-02-10 17:18:43.586 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: azureml-train-automl==1.19.0.*
2021-02-10 17:18:43.587 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package pandas missing from dependencies file.
2021-02-10 17:18:43.587 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: pandas==0.25.1
2021-02-10 17:18:43.588 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package psutil missing from dependencies file.
2021-02-10 17:18:43.588 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: psutil>5.0.0,<6.0.0
2021-02-10 17:18:43.589 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package scikit-learn missing from dependencies file.
2021-02-10 17:18:43.589 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: scikit-learn==0.22.1
2021-02-10 17:18:43.589 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package numpy missing from dependencies file.
2021-02-10 17:18:43.589 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: numpy~=1.18.0
2021-02-10 17:18:43.590 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package py-xgboost missing from dependencies file.
2021-02-10 17:18:43.590 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: py-xgboost<=0.90
2021-02-10 17:18:43.590 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package inference-schema missing from dependencies file.
2021-02-10 17:18:43.591 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package fbprophet missing from dependencies file.
2021-02-10 17:18:43.591 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: fbprophet==0.5
2021-02-10 17:18:43.592 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package setuptools-git missing from dependencies file.
2021-02-10 17:18:43.596 - INFO - 275796 - azureml.train.automl._azureautomlclient._validate_input:663 - Start data validation.
2021-02-10 17:18:46.725 - CRITICAL - 275796 - azureml.train.automl._azureautomlclient.log_traceback:224 - Type: ValidationError
Class: ValidationException
Message: ValidationException:
	Message: Validation error(s): [{
    "additional_properties": {
        "debugInfo": null
    },
    "code": "UserError",
    "severity": 2,
    "message": "Y is empty",
    "message_format": "{dataName} is empty",
    "message_parameters": {
        "dataName": "Y"
    },
    "reference_code": null,
    "details_uri": null,
    "target": "training_data",
    "details": [
        {
            "additional_properties": {
                "debugInfo": null
            },
            "code": null,
            "severity": null,
            "message": "null",
            "message_format": null,
            "message_parameters": {},
            "reference_code": null,
            "details_uri": null,
            "target": null,
            "details": [],
            "inner_error": null
        }
    ],
    "inner_error": {
        "additional_properties": {},
        "code": "BadData",
        "inner_error": {
            "additional_properties": {},
            "code": "EmptyData",
            "inner_error": null
        }
    }
}]
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "ValidationError"
        },
        "message": "Validation error(s): [{\n    \"additional_properties\": {\n        \"debugInfo\": null\n    },\n    \"code\": \"UserError\",\n    \"severity\": 2,\n    \"message\": \"Y is empty\",\n    \"message_format\": \"{dataName} is empty\",\n    \"message_parameters\": {\n        \"dataName\": \"Y\"\n    },\n    \"reference_code\": null,\n    \"details_uri\": null,\n    \"target\": \"training_data\",\n    \"details\": [\n        {\n            \"additional_properties\": {\n                \"debugInfo\": null\n            },\n            \"code\": null,\n            \"severity\": null,\n            \"message\": \"null\",\n            \"message_format\": null,\n            \"message_parameters\": {},\n            \"reference_code\": null,\n            \"details_uri\": null,\n            \"target\": null,\n            \"details\": [],\n            \"inner_error\": null\n        }\n    ],\n    \"inner_error\": {\n        \"additional_properties\": {},\n        \"code\": \"BadData\",\n        \"inner_error\": {\n            \"additional_properties\": {},\n            \"code\": \"EmptyData\",\n            \"inner_error\": null\n        }\n    }\n}]"
    }
}
Traceback:
  File "_azureautomlclient.py", line 409, in fit
    test_data=test_data)
  File "_azureautomlclient.py", line 423, in _fit_remote
    validation_data=validation_data, test_data=test_data)
  File "_azureautomlclient.py", line 486, in _fit_remote_core
    training_data=training_data, validation_data=validation_data, test_data=test_data)
  File "_azureautomlclient.py", line 537, in _create_parent_run_for_remote
    test_data=test_data
  File "_azureautomlclient.py", line 616, in _create_and_validate_parent_run_dto
    self._validate_input(parent_run_dto)
  File "_azureautomlclient.py", line 694, in _validate_input
    "Validation failed. Please fix the data or settings following the validation results."

ExceptionTarget: Unspecified
2021-02-10 17:18:46.725 - INFO - 275796 - azureml.train.automl._azureautomlclient._fail_parent_run:846 - No parent run to fail
2021-02-10 17:19:09.141 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package azureml-train-automl missing from dependencies file.
2021-02-10 17:19:09.141 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: azureml-train-automl==1.19.0.*
2021-02-10 17:19:09.141 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package pandas missing from dependencies file.
2021-02-10 17:19:09.142 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: pandas==0.25.1
2021-02-10 17:19:09.142 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package psutil missing from dependencies file.
2021-02-10 17:19:09.142 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: psutil>5.0.0,<6.0.0
2021-02-10 17:19:09.142 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package scikit-learn missing from dependencies file.
2021-02-10 17:19:09.142 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: scikit-learn==0.22.1
2021-02-10 17:19:09.143 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package numpy missing from dependencies file.
2021-02-10 17:19:09.143 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: numpy~=1.18.0
2021-02-10 17:19:09.143 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package py-xgboost missing from dependencies file.
2021-02-10 17:19:09.143 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: py-xgboost<=0.90
2021-02-10 17:19:09.144 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package inference-schema missing from dependencies file.
2021-02-10 17:19:09.144 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package fbprophet missing from dependencies file.
2021-02-10 17:19:09.144 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: fbprophet==0.5
2021-02-10 17:19:09.145 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package setuptools-git missing from dependencies file.
2021-02-10 17:19:09.151 - INFO - 275796 - azureml.train.automl._azureautomlclient._validate_input:663 - Start data validation.
2021-02-10 17:19:13.752 - CRITICAL - 275796 - azureml.train.automl._azureautomlclient.log_traceback:224 - Type: ValidationError
Class: ValidationException
Message: ValidationException:
	Message: Validation error(s): [{
    "additional_properties": {
        "debugInfo": null
    },
    "code": "UserError",
    "severity": 2,
    "message": "Y is empty",
    "message_format": "{dataName} is empty",
    "message_parameters": {
        "dataName": "Y"
    },
    "reference_code": null,
    "details_uri": null,
    "target": "training_data",
    "details": [
        {
            "additional_properties": {
                "debugInfo": null
            },
            "code": null,
            "severity": null,
            "message": "null",
            "message_format": null,
            "message_parameters": {},
            "reference_code": null,
            "details_uri": null,
            "target": null,
            "details": [],
            "inner_error": null
        }
    ],
    "inner_error": {
        "additional_properties": {},
        "code": "BadData",
        "inner_error": {
            "additional_properties": {},
            "code": "EmptyData",
            "inner_error": null
        }
    }
}]
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "ValidationError"
        },
        "message": "Validation error(s): [{\n    \"additional_properties\": {\n        \"debugInfo\": null\n    },\n    \"code\": \"UserError\",\n    \"severity\": 2,\n    \"message\": \"Y is empty\",\n    \"message_format\": \"{dataName} is empty\",\n    \"message_parameters\": {\n        \"dataName\": \"Y\"\n    },\n    \"reference_code\": null,\n    \"details_uri\": null,\n    \"target\": \"training_data\",\n    \"details\": [\n        {\n            \"additional_properties\": {\n                \"debugInfo\": null\n            },\n            \"code\": null,\n            \"severity\": null,\n            \"message\": \"null\",\n            \"message_format\": null,\n            \"message_parameters\": {},\n            \"reference_code\": null,\n            \"details_uri\": null,\n            \"target\": null,\n            \"details\": [],\n            \"inner_error\": null\n        }\n    ],\n    \"inner_error\": {\n        \"additional_properties\": {},\n        \"code\": \"BadData\",\n        \"inner_error\": {\n            \"additional_properties\": {},\n            \"code\": \"EmptyData\",\n            \"inner_error\": null\n        }\n    }\n}]"
    }
}
Traceback:
  File "_azureautomlclient.py", line 409, in fit
    test_data=test_data)
  File "_azureautomlclient.py", line 423, in _fit_remote
    validation_data=validation_data, test_data=test_data)
  File "_azureautomlclient.py", line 486, in _fit_remote_core
    training_data=training_data, validation_data=validation_data, test_data=test_data)
  File "_azureautomlclient.py", line 537, in _create_parent_run_for_remote
    test_data=test_data
  File "_azureautomlclient.py", line 616, in _create_and_validate_parent_run_dto
    self._validate_input(parent_run_dto)
  File "_azureautomlclient.py", line 694, in _validate_input
    "Validation failed. Please fix the data or settings following the validation results."

ExceptionTarget: Unspecified
2021-02-10 17:19:13.753 - INFO - 275796 - azureml.train.automl._azureautomlclient._fail_parent_run:846 - No parent run to fail
2021-02-10 17:19:16.210 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package azureml-train-automl missing from dependencies file.
2021-02-10 17:19:16.211 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: azureml-train-automl==1.19.0.*
2021-02-10 17:19:16.211 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package pandas missing from dependencies file.
2021-02-10 17:19:16.212 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: pandas==0.25.1
2021-02-10 17:19:16.212 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package psutil missing from dependencies file.
2021-02-10 17:19:16.212 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: psutil>5.0.0,<6.0.0
2021-02-10 17:19:16.213 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package scikit-learn missing from dependencies file.
2021-02-10 17:19:16.213 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: scikit-learn==0.22.1
2021-02-10 17:19:16.213 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package numpy missing from dependencies file.
2021-02-10 17:19:16.213 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: numpy~=1.18.0
2021-02-10 17:19:16.214 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package py-xgboost missing from dependencies file.
2021-02-10 17:19:16.214 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: py-xgboost<=0.90
2021-02-10 17:19:16.214 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package inference-schema missing from dependencies file.
2021-02-10 17:19:16.215 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package fbprophet missing from dependencies file.
2021-02-10 17:19:16.215 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: fbprophet==0.5
2021-02-10 17:19:16.215 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package setuptools-git missing from dependencies file.
2021-02-10 17:19:16.221 - INFO - 275796 - azureml.train.automl._azureautomlclient._validate_input:663 - Start data validation.
2021-02-10 17:19:19.646 - CRITICAL - 275796 - azureml.train.automl._azureautomlclient.log_traceback:224 - Type: ValidationError
Class: ValidationException
Message: ValidationException:
	Message: Validation error(s): [{
    "additional_properties": {
        "debugInfo": null
    },
    "code": "UserError",
    "severity": 2,
    "message": "Y is empty",
    "message_format": "{dataName} is empty",
    "message_parameters": {
        "dataName": "Y"
    },
    "reference_code": null,
    "details_uri": null,
    "target": "training_data",
    "details": [
        {
            "additional_properties": {
                "debugInfo": null
            },
            "code": null,
            "severity": null,
            "message": "null",
            "message_format": null,
            "message_parameters": {},
            "reference_code": null,
            "details_uri": null,
            "target": null,
            "details": [],
            "inner_error": null
        }
    ],
    "inner_error": {
        "additional_properties": {},
        "code": "BadData",
        "inner_error": {
            "additional_properties": {},
            "code": "EmptyData",
            "inner_error": null
        }
    }
}]
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "ValidationError"
        },
        "message": "Validation error(s): [{\n    \"additional_properties\": {\n        \"debugInfo\": null\n    },\n    \"code\": \"UserError\",\n    \"severity\": 2,\n    \"message\": \"Y is empty\",\n    \"message_format\": \"{dataName} is empty\",\n    \"message_parameters\": {\n        \"dataName\": \"Y\"\n    },\n    \"reference_code\": null,\n    \"details_uri\": null,\n    \"target\": \"training_data\",\n    \"details\": [\n        {\n            \"additional_properties\": {\n                \"debugInfo\": null\n            },\n            \"code\": null,\n            \"severity\": null,\n            \"message\": \"null\",\n            \"message_format\": null,\n            \"message_parameters\": {},\n            \"reference_code\": null,\n            \"details_uri\": null,\n            \"target\": null,\n            \"details\": [],\n            \"inner_error\": null\n        }\n    ],\n    \"inner_error\": {\n        \"additional_properties\": {},\n        \"code\": \"BadData\",\n        \"inner_error\": {\n            \"additional_properties\": {},\n            \"code\": \"EmptyData\",\n            \"inner_error\": null\n        }\n    }\n}]"
    }
}
Traceback:
  File "_azureautomlclient.py", line 409, in fit
    test_data=test_data)
  File "_azureautomlclient.py", line 423, in _fit_remote
    validation_data=validation_data, test_data=test_data)
  File "_azureautomlclient.py", line 486, in _fit_remote_core
    training_data=training_data, validation_data=validation_data, test_data=test_data)
  File "_azureautomlclient.py", line 537, in _create_parent_run_for_remote
    test_data=test_data
  File "_azureautomlclient.py", line 616, in _create_and_validate_parent_run_dto
    self._validate_input(parent_run_dto)
  File "_azureautomlclient.py", line 694, in _validate_input
    "Validation failed. Please fix the data or settings following the validation results."

ExceptionTarget: Unspecified
2021-02-10 17:19:19.647 - INFO - 275796 - azureml.train.automl._azureautomlclient._fail_parent_run:846 - No parent run to fail
2021-02-10 17:21:42.909 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package azureml-train-automl missing from dependencies file.
2021-02-10 17:21:42.909 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: azureml-train-automl==1.19.0.*
2021-02-10 17:21:42.910 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package pandas missing from dependencies file.
2021-02-10 17:21:42.910 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: pandas==0.25.1
2021-02-10 17:21:42.910 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package psutil missing from dependencies file.
2021-02-10 17:21:42.911 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: psutil>5.0.0,<6.0.0
2021-02-10 17:21:42.911 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package scikit-learn missing from dependencies file.
2021-02-10 17:21:42.911 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: scikit-learn==0.22.1
2021-02-10 17:21:42.911 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package numpy missing from dependencies file.
2021-02-10 17:21:42.911 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: numpy~=1.18.0
2021-02-10 17:21:42.912 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package py-xgboost missing from dependencies file.
2021-02-10 17:21:42.912 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: py-xgboost<=0.90
2021-02-10 17:21:42.913 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package inference-schema missing from dependencies file.
2021-02-10 17:21:42.913 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package fbprophet missing from dependencies file.
2021-02-10 17:21:42.913 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: fbprophet==0.5
2021-02-10 17:21:42.914 - INFO - 275796 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package setuptools-git missing from dependencies file.
2021-02-10 17:21:42.919 - INFO - 275796 - azureml.train.automl._azureautomlclient._validate_input:663 - Start data validation.
2021-02-10 17:21:46.187 - CRITICAL - 275796 - azureml.train.automl._azureautomlclient.log_traceback:224 - Type: ValidationError
Class: ValidationException
Message: ValidationException:
	Message: Validation error(s): [{
    "additional_properties": {
        "debugInfo": null
    },
    "code": "UserError",
    "severity": 2,
    "message": "Y is empty",
    "message_format": "{dataName} is empty",
    "message_parameters": {
        "dataName": "Y"
    },
    "reference_code": null,
    "details_uri": null,
    "target": "training_data",
    "details": [
        {
            "additional_properties": {
                "debugInfo": null
            },
            "code": null,
            "severity": null,
            "message": "null",
            "message_format": null,
            "message_parameters": {},
            "reference_code": null,
            "details_uri": null,
            "target": null,
            "details": [],
            "inner_error": null
        }
    ],
    "inner_error": {
        "additional_properties": {},
        "code": "BadData",
        "inner_error": {
            "additional_properties": {},
            "code": "EmptyData",
            "inner_error": null
        }
    }
}]
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "ValidationError"
        },
        "message": "Validation error(s): [{\n    \"additional_properties\": {\n        \"debugInfo\": null\n    },\n    \"code\": \"UserError\",\n    \"severity\": 2,\n    \"message\": \"Y is empty\",\n    \"message_format\": \"{dataName} is empty\",\n    \"message_parameters\": {\n        \"dataName\": \"Y\"\n    },\n    \"reference_code\": null,\n    \"details_uri\": null,\n    \"target\": \"training_data\",\n    \"details\": [\n        {\n            \"additional_properties\": {\n                \"debugInfo\": null\n            },\n            \"code\": null,\n            \"severity\": null,\n            \"message\": \"null\",\n            \"message_format\": null,\n            \"message_parameters\": {},\n            \"reference_code\": null,\n            \"details_uri\": null,\n            \"target\": null,\n            \"details\": [],\n            \"inner_error\": null\n        }\n    ],\n    \"inner_error\": {\n        \"additional_properties\": {},\n        \"code\": \"BadData\",\n        \"inner_error\": {\n            \"additional_properties\": {},\n            \"code\": \"EmptyData\",\n            \"inner_error\": null\n        }\n    }\n}]"
    }
}
Traceback:
  File "_azureautomlclient.py", line 409, in fit
    test_data=test_data)
  File "_azureautomlclient.py", line 423, in _fit_remote
    validation_data=validation_data, test_data=test_data)
  File "_azureautomlclient.py", line 486, in _fit_remote_core
    training_data=training_data, validation_data=validation_data, test_data=test_data)
  File "_azureautomlclient.py", line 537, in _create_parent_run_for_remote
    test_data=test_data
  File "_azureautomlclient.py", line 616, in _create_and_validate_parent_run_dto
    self._validate_input(parent_run_dto)
  File "_azureautomlclient.py", line 694, in _validate_input
    "Validation failed. Please fix the data or settings following the validation results."

ExceptionTarget: Unspecified
2021-02-10 17:21:46.188 - INFO - 275796 - azureml.train.automl._azureautomlclient._fail_parent_run:846 - No parent run to fail
